### DISCUSSION TITLE
Changing DNS for Kong Admin Connection in Kong Manager (K8S)

### DISCUSSION THREAD

**Discussion by vinicius-meutudoapp** [Kong/kong-manager#198] [Q&A]
Hello,

I'm currently configuring Kong Manager to access our Kong Admin API, and we've encountered an interesting challenge. Our setup involves Kong Manager being accessed through a specific DNS (https://kong-manager.mydomain.com/manager), which successfully redirects to our Kubernetes service on port 8002. However, Kong Manager then attempts to connect to the Kong Admin API through the same DNS but on a different port (https://kong-manager.mydomain.com:8444). This results in a failure because the ingress configuration doesn't know how to route the traffic for port 8444.

Is there a way to configure Kong Manager (or the ingress) to either:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-ingress
  annotations:
    kubernetes.io/ingress.class: nginx-private
spec:
  rules:
    - host: kong-manager.mydomain.com
      http:
        paths:
          - backend:
              service:
                name: kong-service
                port:
                  number: 8002
            path: /
            pathType: ImplementationSpecific
```

Change the DNS or port that Kong Manager uses to connect to the Kong Admin API, aligning it with our ingress setup?
Directly manage the port forwarding within the Kubernetes service or ingress configuration to handle this use case?
Any guidance on how to approach this situation would be greatly appreciated, especially if there are best practices for configuring Kong Manager and Kong Admin API interactions in a Kubernetes environment.

Thank you for your help!
