### DISCUSSION TITLE
Hope to add docker configuration

### DISCUSSION THREAD

**Discussion by onepiecewyz** [Kong/kong-manager#85] [Ideas]
The UI is really awesome, and I hope Docker configuration can be provided as soon as possible.

**Comment by sumimakito** [comment]
Hello @onepiecewyz, do you refer to an example Docker Compose file to start a Kong Gateway OSS with Kong Manager OSS?

The following YAML would help you quickly set up a Kong Gateway OSS instance with Kong Manager OSS available at the `:8002` port on your Docker host:


```yaml
version: "3.9"

services:
  kong:
    image: kong/kong:3.4
    ports:
      - "8000-8002:8000-8002"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG_STRING: '{"_format_version":"1.1", "services":[{"host":"mockbin.com","port":443,"protocol":"https", "routes":[{"paths":["/"]}]}],"plugins":[{"name":"rate-limiting", "config":{"policy":"local","limit_by":"ip","minute":3}}]}'
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    restart: always

```
